version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: dockerfile
    expose:
      - 8000
    environment:
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - SECRET_KEY=secret-key-goes-here
      - DATABASE_URL=postgresql://hello_flask:hello_flask@db:5432/hello_flask_dev
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    # ports:
    #   - 5432:5432
  
  nginx:
    image: nginx:1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/flask_app.conf:ro
      - ./instance:/etc/ssl/private/
    depends_on:
      - web


volumes:
  postgres_data: